language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - 'sudo apt-get install redis-server'
install:
  - 'pip install Flask'
  - 'pip install pytz'
  - 'pip install python-dateutil'
  - 'pip install Beaker>=1.6.4'
  - 'pip install redis>=2.10'
script: py.test
